// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public interface CancelSessionTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.cloud.broker.protobuf.CancelSessionTokenResponse)
    com.google.protobuf.MessageOrBuilder {
}
