// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public interface CancelSessionTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.cloud.broker.protobuf.CancelSessionTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string session_token = 1;</code>
   */
  java.lang.String getSessionToken();
  /**
   * <code>string session_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getSessionTokenBytes();
}
