// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public interface GetAccessTokenRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.cloud.broker.protobuf.GetAccessTokenRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string scope = 1;</code>
   */
  java.lang.String getScope();
  /**
   * <code>string scope = 1;</code>
   */
  com.google.protobuf.ByteString
      getScopeBytes();

  /**
   * <code>string owner = 2;</code>
   */
  java.lang.String getOwner();
  /**
   * <code>string owner = 2;</code>
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>string target = 3;</code>
   */
  java.lang.String getTarget();
  /**
   * <code>string target = 3;</code>
   */
  com.google.protobuf.ByteString
      getTargetBytes();
}
