// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public interface GetAccessTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.cloud.broker.protobuf.GetAccessTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string access_token = 1;</code>
   */
  java.lang.String getAccessToken();
  /**
   * <code>string access_token = 1;</code>
   */
  com.google.protobuf.ByteString
      getAccessTokenBytes();

  /**
   * <code>int64 expires_at = 2;</code>
   */
  long getExpiresAt();
}
