// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public interface RenewSessionTokenResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 expires_at = 2;</code>
   */
  long getExpiresAt();
}
