// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

/**
 * Protobuf type {@code com.google.cloud.broker.protobuf.RenewSessionTokenResponse}
 */
public  final class RenewSessionTokenResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
    RenewSessionTokenResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use RenewSessionTokenResponse.newBuilder() to construct.
  private RenewSessionTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private RenewSessionTokenResponse() {
    expiresAt_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private RenewSessionTokenResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 16: {

            expiresAt_ = input.readInt64();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.google.cloud.broker.protobuf.BrokerProto.internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.google.cloud.broker.protobuf.BrokerProto.internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.google.cloud.broker.protobuf.RenewSessionTokenResponse.class, com.google.cloud.broker.protobuf.RenewSessionTokenResponse.Builder.class);
  }

  public static final int EXPIRES_AT_FIELD_NUMBER = 2;
  private long expiresAt_;
  /**
   * <code>int64 expires_at = 2;</code>
   */
  public long getExpiresAt() {
    return expiresAt_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (expiresAt_ != 0L) {
      output.writeInt64(2, expiresAt_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (expiresAt_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, expiresAt_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.google.cloud.broker.protobuf.RenewSessionTokenResponse)) {
      return super.equals(obj);
    }
    com.google.cloud.broker.protobuf.RenewSessionTokenResponse other = (com.google.cloud.broker.protobuf.RenewSessionTokenResponse) obj;

    boolean result = true;
    result = result && (getExpiresAt()
        == other.getExpiresAt());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + EXPIRES_AT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getExpiresAt());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.google.cloud.broker.protobuf.RenewSessionTokenResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.google.cloud.broker.protobuf.RenewSessionTokenResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
      com.google.cloud.broker.protobuf.RenewSessionTokenResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.google.cloud.broker.protobuf.BrokerProto.internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.google.cloud.broker.protobuf.BrokerProto.internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.google.cloud.broker.protobuf.RenewSessionTokenResponse.class, com.google.cloud.broker.protobuf.RenewSessionTokenResponse.Builder.class);
    }

    // Construct using com.google.cloud.broker.protobuf.RenewSessionTokenResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      expiresAt_ = 0L;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.google.cloud.broker.protobuf.BrokerProto.internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor;
    }

    @java.lang.Override
    public com.google.cloud.broker.protobuf.RenewSessionTokenResponse getDefaultInstanceForType() {
      return com.google.cloud.broker.protobuf.RenewSessionTokenResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.google.cloud.broker.protobuf.RenewSessionTokenResponse build() {
      com.google.cloud.broker.protobuf.RenewSessionTokenResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.google.cloud.broker.protobuf.RenewSessionTokenResponse buildPartial() {
      com.google.cloud.broker.protobuf.RenewSessionTokenResponse result = new com.google.cloud.broker.protobuf.RenewSessionTokenResponse(this);
      result.expiresAt_ = expiresAt_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.google.cloud.broker.protobuf.RenewSessionTokenResponse) {
        return mergeFrom((com.google.cloud.broker.protobuf.RenewSessionTokenResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.google.cloud.broker.protobuf.RenewSessionTokenResponse other) {
      if (other == com.google.cloud.broker.protobuf.RenewSessionTokenResponse.getDefaultInstance()) return this;
      if (other.getExpiresAt() != 0L) {
        setExpiresAt(other.getExpiresAt());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.google.cloud.broker.protobuf.RenewSessionTokenResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.google.cloud.broker.protobuf.RenewSessionTokenResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long expiresAt_ ;
    /**
     * <code>int64 expires_at = 2;</code>
     */
    public long getExpiresAt() {
      return expiresAt_;
    }
    /**
     * <code>int64 expires_at = 2;</code>
     */
    public Builder setExpiresAt(long value) {
      
      expiresAt_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 expires_at = 2;</code>
     */
    public Builder clearExpiresAt() {
      
      expiresAt_ = 0L;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
  }

  // @@protoc_insertion_point(class_scope:com.google.cloud.broker.protobuf.RenewSessionTokenResponse)
  private static final com.google.cloud.broker.protobuf.RenewSessionTokenResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.google.cloud.broker.protobuf.RenewSessionTokenResponse();
  }

  public static com.google.cloud.broker.protobuf.RenewSessionTokenResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<RenewSessionTokenResponse>
      PARSER = new com.google.protobuf.AbstractParser<RenewSessionTokenResponse>() {
    @java.lang.Override
    public RenewSessionTokenResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new RenewSessionTokenResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<RenewSessionTokenResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<RenewSessionTokenResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.cloud.broker.protobuf.RenewSessionTokenResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

