// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: broker.proto

package com.google.cloud.broker.protobuf;

public final class BrokerProto {
  private BrokerProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_GetSessionTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_GetSessionTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_GetAccessTokenRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_google_cloud_broker_protobuf_GetAccessTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014broker.proto\022 com.google.cloud.broker." +
      "protobuf\"W\n\026GetSessionTokenRequest\022\r\n\005sc" +
      "ope\030\001 \001(\t\022\r\n\005owner\030\002 \001(\t\022\016\n\006target\030\003 \001(\t" +
      "\022\017\n\007renewer\030\004 \001(\t\"0\n\027GetSessionTokenResp" +
      "onse\022\025\n\rsession_token\030\001 \001(\t\"1\n\030RenewSess" +
      "ionTokenRequest\022\025\n\rsession_token\030\001 \001(\t\"/" +
      "\n\031RenewSessionTokenResponse\022\022\n\nexpires_a" +
      "t\030\002 \001(\003\"2\n\031CancelSessionTokenRequest\022\025\n\r" +
      "session_token\030\001 \001(\t\"\034\n\032CancelSessionToke" +
      "nResponse\"E\n\025GetAccessTokenRequest\022\r\n\005sc" +
      "ope\030\001 \001(\t\022\r\n\005owner\030\002 \001(\t\022\016\n\006target\030\003 \001(\t" +
      "\"B\n\026GetAccessTokenResponse\022\024\n\014access_tok" +
      "en\030\001 \001(\t\022\022\n\nexpires_at\030\002 \001(\0032\300\004\n\006Broker\022" +
      "\210\001\n\017GetSessionToken\0228.com.google.cloud.b" +
      "roker.protobuf.GetSessionTokenRequest\0329." +
      "com.google.cloud.broker.protobuf.GetSess" +
      "ionTokenResponse\"\000\022\216\001\n\021RenewSessionToken" +
      "\022:.com.google.cloud.broker.protobuf.Rene" +
      "wSessionTokenRequest\032;.com.google.cloud." +
      "broker.protobuf.RenewSessionTokenRespons" +
      "e\"\000\022\221\001\n\022CancelSessionToken\022;.com.google." +
      "cloud.broker.protobuf.CancelSessionToken" +
      "Request\032<.com.google.cloud.broker.protob" +
      "uf.CancelSessionTokenResponse\"\000\022\205\001\n\016GetA" +
      "ccessToken\0227.com.google.cloud.broker.pro" +
      "tobuf.GetAccessTokenRequest\0328.com.google" +
      ".cloud.broker.protobuf.GetAccessTokenRes" +
      "ponse\"\000B1\n com.google.cloud.broker.proto" +
      "bufB\013BrokerProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_GetSessionTokenRequest_descriptor,
        new java.lang.String[] { "Scope", "Owner", "Target", "Renewer", });
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_google_cloud_broker_protobuf_GetSessionTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_GetSessionTokenResponse_descriptor,
        new java.lang.String[] { "SessionToken", });
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenRequest_descriptor,
        new java.lang.String[] { "SessionToken", });
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_RenewSessionTokenResponse_descriptor,
        new java.lang.String[] { "ExpiresAt", });
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenRequest_descriptor,
        new java.lang.String[] { "SessionToken", });
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_CancelSessionTokenResponse_descriptor,
        new java.lang.String[] { });
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_GetAccessTokenRequest_descriptor,
        new java.lang.String[] { "Scope", "Owner", "Target", });
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_com_google_cloud_broker_protobuf_GetAccessTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_google_cloud_broker_protobuf_GetAccessTokenResponse_descriptor,
        new java.lang.String[] { "AccessToken", "ExpiresAt", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
